### ISSUE TITLE
hack facile pour rentrer dans le code ?

### ISSUE THREAD

**Issue by berteh** [vingtcent123/ouvretaferme#21]
Bonjour.

Votre logiciel m'inspire quant aux fonctionnalités déjà implémentées. Avant de décider de l'adopter (ou non) je voudrais plonger un peu plus dans le code.
Avez vous un conseil sur un mini bug à fixer ou un mini hack qui vous serait utile et me permettrait de découvrir l'architecture du code ?
Je suis à l'aise en PHP, SQL, CSS, moyen en JS, et ne connais pas votre framework (lime?).

Bonne journée. 
Berteh.

**Comment by vingtcent123** [comment]
Bonjour,

Je viens de créer un fichier INSTALL.md sur le dépôt pour installer le site en local :
https://github.com/vingtcent123/ouvretaferme/blob/main/INSTALL.md

_lime_ est un framework maison, pour lequel il n'existe pas vraiment de documentation.
On retrouve évidemment des similitudes avec d'autres frameworks type laravel, mais la prise en main risque d'être un peu délicate.

Il n'y a pas de bug à corriger, je suis à jour à ce niveau là.
Pour les fonctionnalités, un petit truc au niveau des factures :
![image](https://github.com/vingtcent123/ouvretaferme/assets/12171224/d2f01b78-b56a-478b-a91e-5be23f501ec3)

Il s'agirait de remplacer la coche et la croix cliquables dans la colonne "Réglée",  par un toggle plus visuel:
![image](https://github.com/vingtcent123/ouvretaferme/assets/12171224/70ab470f-eb20-44d4-bb70-d65d2b5fbae3)


Le toggle est déjà utilisé sur la page des produits et des clients par exemple pour les activer/désactiver.


Bon courage si tu veux te lancer!
Je peux essayer de t'apporter un peu de support si tu veux te lancer, mais je suis en pleine saison de maraichage, et habituellement j'ai plus de temps à consacrer à OTF de la fin de l'automne au début du printemps.

**Comment by berteh** [comment]
merci et ok: j'y regarderai dès déploiement sur ma machine de dev.
 
bonnes plantations et bonnes récoltes ! (j'attends mes premières tomates avec impatience ;)
